#include <gtest/gtest.h>
#include "vm/VM.hpp"
#include "vm/Value.hpp"
#include "vm/Object.hpp"
#include "vm/Opcode.hpp"
#include "vm/CallFrame.hpp"
#include "vm/GC.hpp"
#include "vm/Builtins.hpp"
#include "IR/IRGenerator.hpp"
#include "bytecode/BytecodeGenerator.hpp"
#include "semantic/SemanticAnalyzer.hpp"
#include "parser/Parser.hpp"
#include "lexer/lexer.hpp"
#include "error/ErrorReporter.hpp"
#include <memory>
#include <sstream>

using namespace volta::vm;
using namespace volta::semantic;
using namespace volta::parser;
using namespace volta::lexer;
using namespace volta::errors;

// ============================================================================
// Test Fixture for Full Pipeline Tests
// ============================================================================

class VMIntegrationTest : public ::testing::Test {
protected:
    std::unique_ptr<ErrorReporter> errorReporter;
    std::unique_ptr<SemanticAnalyzer> analyzer;
    std::unique_ptr<VM> vm;

    void SetUp() override {
        errorReporter = std::make_unique<ErrorReporter>();
        analyzer = std::make_unique<SemanticAnalyzer>(*errorReporter);
        vm = std::make_unique<VM>();
    }

    // Parse source code into AST
    std::unique_ptr<volta::ast::Program> parseSource(const std::string& source) {
        Lexer lexer(source);
        auto tokens = lexer.tokenize();
        Parser parser(tokens);
        return parser.parseProgram();
    }

    // Run full pipeline: source -> AST -> type check -> IR -> bytecode -> execute
    std::pair<bool, Value> executeSource(const std::string& source) {
        // Step 1: Lex and parse
        auto ast = parseSource(source);
        if (!ast) {
            return {false, Value::none()};
        }

        // Step 2: Semantic analysis
        bool typeCheckSuccess = analyzer->analyze(*ast);
        if (!typeCheckSuccess || errorReporter->hasErrors()) {
            return {false, Value::none()};
        }

        // Step 3: IR generation
        volta::ir::IRGenerator irGen(*errorReporter);
        auto irModule = irGen.generate(*ast, *analyzer);
        if (!irModule || errorReporter->hasErrors()) {
            return {false, Value::none()};
        }

        // Step 4: Bytecode generation
        volta::bytecode::BytecodeGenerator bytecodeGen(*irModule);
        std::vector<uint8_t> bytecode = bytecodeGen.generate();

        // Step 5: Execute
        // TODO: Actually execute the bytecode with the VM
        // For now, just verify we successfully generated bytecode
        // for (auto byte : bytecode) {
        //     std::cout << byte;
        // }
        return {bytecode.size() > 0, Value::none()};
    }
};

// ============================================================================
// Value Tests
// ============================================================================

TEST(VMValueTest, CreateNone) {
    Value v = Value::none();
    EXPECT_TRUE(v.is_none());
    EXPECT_FALSE(v.is_int());
    EXPECT_FALSE(v.is_float());
    EXPECT_FALSE(v.is_bool());
    EXPECT_FALSE(v.is_object());
}

TEST(VMValueTest, CreateBool) {
    Value vTrue = Value::bool_value(true);
    Value vFalse = Value::bool_value(false);

    EXPECT_TRUE(vTrue.is_bool());
    EXPECT_TRUE(vFalse.is_bool());
    EXPECT_TRUE(vTrue.as_bool());
    EXPECT_FALSE(vFalse.as_bool());
}

TEST(VMValueTest, CreateInt) {
    Value v = Value::int_value(42);

    EXPECT_TRUE(v.is_int());
    EXPECT_EQ(v.as_int(), 42);
}

TEST(VMValueTest, CreateFloat) {
    Value v = Value::float_value(3.14);

    EXPECT_TRUE(v.is_float());
    EXPECT_DOUBLE_EQ(v.as_float(), 3.14);
}

TEST(VMValueTest, ValueEquality) {
    Value int1 = Value::int_value(42);
    Value int2 = Value::int_value(42);
    Value int3 = Value::int_value(99);

    EXPECT_TRUE(int1.equals(int2));
    EXPECT_FALSE(int1.equals(int3));
    EXPECT_TRUE(int1 != int3);  // Operator overload test
}

TEST(VMValueTest, ValueToBool) {
    // Test truthiness conversion
    EXPECT_FALSE(Value::none().to_bool());
    EXPECT_FALSE(Value::bool_value(false).to_bool());
    EXPECT_TRUE(Value::bool_value(true).to_bool());
    EXPECT_FALSE(Value::int_value(0).to_bool());
    EXPECT_TRUE(Value::int_value(42).to_bool());
    EXPECT_FALSE(Value::float_value(0.0).to_bool());
    EXPECT_TRUE(Value::float_value(3.14).to_bool());
}

TEST(VMValueTest, ValueToNumber) {
    // Test numeric conversions
    Value intVal = Value::int_value(42);
    Value floatVal = Value::float_value(3.14);

    EXPECT_DOUBLE_EQ(intVal.to_number(), 42.0);
    EXPECT_DOUBLE_EQ(floatVal.to_number(), 3.14);
}

TEST(VMValueTest, ValueToString) {
    // Test string conversions
    EXPECT_EQ(Value::none().to_string(), "none");
    EXPECT_EQ(Value::bool_value(true).to_string(), "true");
    EXPECT_EQ(Value::bool_value(false).to_string(), "false");
    EXPECT_EQ(Value::int_value(42).to_string(), "42");
    EXPECT_EQ(Value::float_value(3.14).to_string(), "3.14");
}

// ============================================================================
// Object Tests
// ============================================================================

TEST(VMObjectTest, CreateStringObject) {
    VM vm;
    StringObject* str = StringObject::create(&vm, "hello", 5);

    ASSERT_NE(str, nullptr);
    EXPECT_TRUE(str->is_string());
    EXPECT_EQ(str->length, 5);
    EXPECT_STREQ(str->data, "hello");  // Use STREQ for C strings
}

TEST(VMObjectTest, CreateArrayObject) {
    VM vm;
    ArrayObject* arr = ArrayObject::create(&vm, 10);

    ASSERT_NE(arr, nullptr);
    EXPECT_TRUE(arr->is_array());
    EXPECT_EQ(arr->length, 10);
    EXPECT_EQ(arr->capacity, 10);
}

TEST(VMObjectTest, ArrayGetSet) {
    VM vm;
    ArrayObject* arr = ArrayObject::create(&vm, 3);

    arr->set(0, Value::int_value(10));
    arr->set(1, Value::int_value(20));
    arr->set(2, Value::int_value(30));

    EXPECT_EQ(arr->get(0).as_int(), 10);
    EXPECT_EQ(arr->get(1).as_int(), 20);
    EXPECT_EQ(arr->get(2).as_int(), 30);
}

TEST(VMObjectTest, CreateStructObject) {
    VM vm;
    StructObject* obj = StructObject::create(&vm, 2);

    ASSERT_NE(obj, nullptr);
    EXPECT_TRUE(obj->is_struct());
    EXPECT_EQ(obj->field_count, 2);
}

TEST(VMObjectTest, StructGetSet) {
    VM vm;
    StructObject* point = StructObject::create(&vm, 2);

    point->set(0, Value::float_value(3.0));  // x
    point->set(1, Value::float_value(4.0));  // y

    EXPECT_DOUBLE_EQ(point->get(0).as_float(), 3.0);
    EXPECT_DOUBLE_EQ(point->get(1).as_float(), 4.0);
}

TEST(VMObjectTest, ObjectSize) {
    VM vm;

    StringObject* str = StringObject::create(&vm, "hello", 5);
    size_t strSize = object_size(str);
    EXPECT_GT(strSize, 0);

    ArrayObject* arr = ArrayObject::create(&vm, 10);
    size_t arrSize = object_size(arr);
    EXPECT_GT(arrSize, 0);

    StructObject* obj = StructObject::create(&vm, "Point", 2);
    size_t objSize = object_size(obj);
    EXPECT_GT(objSize, 0);
}

// ============================================================================
// Opcode Tests
// ============================================================================

TEST(VMOpcodeTest, OpcodeNames) {
    EXPECT_EQ(opcode_name(Opcode::LOAD_CONST), "LOAD_CONST");
    EXPECT_EQ(opcode_name(Opcode::ADD), "ADD");
    EXPECT_EQ(opcode_name(Opcode::SUB), "SUB");
    EXPECT_EQ(opcode_name(Opcode::MUL), "MUL");
    EXPECT_EQ(opcode_name(Opcode::DIV), "DIV");
    EXPECT_EQ(opcode_name(Opcode::JMP), "JMP");
    EXPECT_EQ(opcode_name(Opcode::CALL), "CALL");
    EXPECT_EQ(opcode_name(Opcode::RETURN), "RETURN");
    EXPECT_EQ(opcode_name(Opcode::PRINT), "PRINT");
    EXPECT_EQ(opcode_name(Opcode::HALT), "HALT");
}

TEST(VMOpcodeTest, OpcodeOperandCounts) {
    // opcode_operand_count returns total BYTES, not logical operand count
    EXPECT_EQ(opcode_operand_count(Opcode::HALT), 0);
    EXPECT_EQ(opcode_operand_count(Opcode::LOAD_CONST), 3);  // ra (1 byte) + kx (2 bytes)
    EXPECT_EQ(opcode_operand_count(Opcode::ADD), 3);         // ra, rb, rc (1 byte each)
    EXPECT_EQ(opcode_operand_count(Opcode::JMP), 3);         // offset (3 bytes)
    EXPECT_EQ(opcode_operand_count(Opcode::CALL), 3);        // ra, rb, rc (function, argc, dst)
}

// ============================================================================
// CallFrame Tests
// ============================================================================

TEST(VMCallFrameTest, InitializeFrame) {
    // CallFrame frame("main", 0);

    // EXPECT_EQ(frame.function_name, "main");
    // EXPECT_EQ(frame.return_address, 0);
    // EXPECT_EQ(frame.return_register, 0);
    // EXPECT_EQ(frame.closure, nullptr);

    // // All registers should be initialized to none
    // for (int i = 0; i < 256; i++) {
    //     EXPECT_TRUE(frame.registers[i].is_none());
    // }
}

TEST(VMCallFrameTest, RegisterAccess) {
    // CallFrame frame("test", 0);

    // frame.registers[0] = Value::int_value(42);
    // frame.registers[1] = Value::float_value(3.14);
    // frame.registers[255] = Value::bool_value(true);

    // EXPECT_EQ(frame.registers[0].as_int(), 42);
    // EXPECT_DOUBLE_EQ(frame.registers[1].as_float(), 3.14);
    // EXPECT_TRUE(frame.registers[255].as_bool());
}

// ============================================================================
// VM Basic Operation Tests
// ============================================================================

TEST(VMBasicTest, VMInitialization) {
    VM vm;

    // VM should initialize without errors
    EXPECT_NE(&vm, nullptr);
}

TEST(VMBasicTest, RegisterBuiltins) {
    VM vm;
    vm.register_builtins();

    // Builtins should be registered
    // TODO: Add way to query registered functions
    SUCCEED();
}

TEST(VMBasicTest, AddConstant) {
    VM vm;

    size_t idx1 = vm.add_constant(Value::int_value(42));
    size_t idx2 = vm.add_constant(Value::float_value(3.14));
    size_t idx3 = vm.add_constant(Value::int_value(42));  // Duplicate

    EXPECT_EQ(idx1, 0);
    EXPECT_EQ(idx2, 1);
    EXPECT_EQ(idx3, 2);  // May be deduplicated or not
}

TEST(VMBasicTest, GetConstant) {
    VM vm;

    size_t idx = vm.add_constant(Value::int_value(42));
    Value val = vm.get_constant(idx);

    EXPECT_TRUE(val.is_int());
    EXPECT_EQ(val.as_int(), 42);
}

TEST(VMBasicTest, GlobalVariables) {
    VM vm;

    vm.set_global("x", Value::int_value(42));
    EXPECT_TRUE(vm.has_global("x"));

    Value val = vm.get_global("x");
    EXPECT_TRUE(val.is_int());
    EXPECT_EQ(val.as_int(), 42);

    EXPECT_FALSE(vm.has_global("y"));
}

TEST(VMBasicTest, AllocateObject) {
    VM vm;

    StringObject* str = (StringObject*)vm.allocate_object(
        sizeof(StringObject) + 6,
        ObjectType::STRING
    );

    ASSERT_NE(str, nullptr);
    EXPECT_TRUE(str->is_string());
}

// ============================================================================
// Builtin Function Tests
// ============================================================================

TEST(VMBuiltinTest, BuiltinPrint) {
    VM vm;

    std::vector<Value> args = {Value::int_value(42)};

    // Redirect stdout to capture output
    testing::internal::CaptureStdout();
    Value result = builtin_print(&vm, args);
    std::string output = testing::internal::GetCapturedStdout();

    EXPECT_TRUE(result.is_none());
    EXPECT_EQ(output, "42");
}

TEST(VMBuiltinTest, BuiltinPrintln) {
    VM vm;

    std::vector<Value> args = {Value::int_value(42)};

    // Redirect stdout to capture output
    testing::internal::CaptureStdout();
    Value result = builtin_println(&vm, args);
    std::string output = testing::internal::GetCapturedStdout();

    EXPECT_TRUE(result.is_none());
    EXPECT_EQ(output, "42\n");
}

TEST(VMBuiltinTest, BuiltinLen_Array) {
    VM vm;

    ArrayObject* arr = ArrayObject::create(&vm, 5);
    std::vector<Value> args = {Value::object_value(arr)};

    Value result = builtin_len(&vm, args);

    EXPECT_TRUE(result.is_int());
    EXPECT_EQ(result.as_int(), 5);
}

TEST(VMBuiltinTest, BuiltinLen_String) {
    VM vm;

    StringObject* str = StringObject::create(&vm, "hello", 5);
    std::vector<Value> args = {Value::object_value(str)};

    Value result = builtin_len(&vm, args);

    EXPECT_TRUE(result.is_int());
    EXPECT_EQ(result.as_int(), 5);
}

TEST(VMBuiltinTest, BuiltinType) {
    VM vm;

    std::vector<Value> args = {Value::int_value(42)};
    Value result = builtin_type(&vm, args);

    EXPECT_TRUE(result.is_object());
    StringObject* typeStr = (StringObject*)result.as_object();
    EXPECT_STREQ(typeStr->data, "int");
}

TEST(VMBuiltinTest, BuiltinStr) {
    VM vm;

    std::vector<Value> args = {Value::int_value(42)};
    Value result = builtin_str(&vm, args);

    EXPECT_TRUE(result.is_object());
    StringObject* str = (StringObject*)result.as_object();
    EXPECT_STREQ(str->data, "42");
}

TEST(VMBuiltinTest, BuiltinInt_FromFloat) {
    VM vm;

    std::vector<Value> args = {Value::float_value(3.14)};
    Value result = builtin_int(&vm, args);

    EXPECT_TRUE(result.is_int());
    EXPECT_EQ(result.as_int(), 3);  // Truncated
}

TEST(VMBuiltinTest, BuiltinInt_FromString) {
    VM vm;

    StringObject* str = StringObject::create(&vm, "42", 2);
    std::vector<Value> args = {Value::object_value(str)};

    Value result = builtin_int(&vm, args);

    EXPECT_TRUE(result.is_int());
    EXPECT_EQ(result.as_int(), 42);
}

TEST(VMBuiltinTest, BuiltinFloat_FromInt) {
    VM vm;

    std::vector<Value> args = {Value::int_value(42)};
    Value result = builtin_float(&vm, args);

    EXPECT_TRUE(result.is_float());
    EXPECT_DOUBLE_EQ(result.as_float(), 42.0);
}

TEST(VMBuiltinTest, BuiltinFloat_FromString) {
    VM vm;

    StringObject* str = StringObject::create(&vm, "3.14", 4);
    std::vector<Value> args = {Value::object_value(str)};

    Value result = builtin_float(&vm, args);

    EXPECT_TRUE(result.is_float());
    EXPECT_DOUBLE_EQ(result.as_float(), 3.14);
}

TEST(VMBuiltinTest, BuiltinAssert_Success) {
    VM vm;

    std::vector<Value> args = {Value::bool_value(true)};

    // Should not throw
    EXPECT_NO_THROW({
        Value result = builtin_assert(&vm, args);
        EXPECT_TRUE(result.is_none());
    });
}

TEST(VMBuiltinTest, BuiltinAssert_Failure) {
    VM vm;

    std::vector<Value> args = {Value::bool_value(false)};

    // Should throw runtime error
    EXPECT_THROW({
        builtin_assert(&vm, args);
    }, std::runtime_error);
}

TEST(VMBuiltinTest, BuiltinAssert_WithMessage) {
    VM vm;

    StringObject* msg = StringObject::create(&vm, "x must be positive", 18);
    std::vector<Value> args = {Value::bool_value(false), Value::object_value(msg)};

    // Should throw with custom message
    try {
        builtin_assert(&vm, args);
        FAIL() << "Expected runtime_error";
    } catch (const std::runtime_error& e) {
        std::string errorMsg = e.what();
        EXPECT_TRUE(errorMsg.find("x must be positive") != std::string::npos);
    }
}

// ============================================================================
// Garbage Collection Tests
// ============================================================================

// TEST(VMGCTest, GCInitialization) {
//     GarbageCollector gc;

//     // GC should initialize without errors
//     EXPECT_NE(&gc, nullptr);
// }

// TEST(VMGCTest, GCPauseResume) {
//     GarbageCollector gc;

//     gc.pause();
//     // GC should be paused

//     gc.resume();
//     // GC should be resumed

//     SUCCEED();
// }

// TEST(VMGCTest, AllocateAndCollect) {
//     VM vm;

//     // Allocate many objects to trigger GC
//     for (int i = 0; i < 1000; i++) {
//         StringObject::create(&vm, "test", 4);
//     }

//     // Force GC collection
//     // TODO: Add explicit GC collection method

//     SUCCEED();
// }

// ============================================================================
// Integration Tests: Full Pipeline
// ============================================================================

TEST_F(VMIntegrationTest, SimpleVariableDeclaration) {
    const char* source = R"(
        x: int = 42
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, SimpleArithmetic) {
    const char* source = R"(
        x: int = 10 + 20
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, FunctionDefinition) {
    const char* source = R"(
        fn add(a: int, b: int) -> int {
            return a + b
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, FunctionCall) {
    const char* source = R"(
        fn double(x: int) -> int {
            return x * 2
        }

        result := double(21)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, IfStatement) {
    const char* source = R"(
        x: int = 10
        if x > 5 {
            x = 20
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, WhileLoop) {
    const char* source = R"(
        x: int = 0
        while x < 10 {
            x = x + 1
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, ForLoop) {
    const char* source = R"(
        sum: int = 0
        for i in 0..10 {
            sum = sum + i
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, ArrayCreation) {
    const char* source = R"(
        arr: [int] = [1, 2, 3, 4, 5]
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, ArrayIndexing) {
    const char* source = R"(
        arr: [int] = [10, 20, 30]
        x: int = arr[1]
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, StructDefinition) {
    const char* source = R"(
        struct Point {
            x: float
            y: float
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, StructLiteral) {
    const char* source = R"(
        struct Point {
            x: float
            y: float
        }

        p: Point = Point { x: 3.0, y: 4.0 }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, StructMethodCall) {
    const char* source = R"(
        struct Point {
            x: float
            y: float
        }

        fn Point.distance(self: Point) -> float {
            return self.x * self.x + self.y * self.y
        }

        p: Point = Point { x: 3.0, y: 4.0 }
        dist: float = p.distance()
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, PrintFunction) {
    const char* source = R"(
        print("Hello, World!")
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, RecursiveFunction) {
    const char* source = R"(
        fn factorial(n: int) -> int {
            if n <= 1 {
                return 1
            }
            return n * factorial(n - 1)
        }

        result := factorial(5)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, NestedFunctions) {
    const char* source = R"(
        fn outer(x: int) -> int {
            fn inner(y: int) -> int {
                return y * 2
            }
            return inner(x) + 10
        }

        result := outer(5)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, ComplexExpression) {
    const char* source = R"(
        x: int = (10 + 20) * 3 - 15 / 5
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, BooleanLogic) {
    const char* source = R"(
        x: bool = true and false or true
        y: bool = not (x and true)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, StringConcatenation) {
    const char* source = R"(
        str: string = "Hello, " + "World!"
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, TypeConversions) {
    const char* source = R"(
        x: int = 42
        y: float = float(x)
        z: string = str(y)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

// ============================================================================
// Error Handling Tests
// ============================================================================

TEST_F(VMIntegrationTest, DivisionByZero) {
    const char* source = R"(
        x: int = 10 / 0
    )";

    // Should complete pipeline but may fail at runtime
    auto [success, result] = executeSource(source);
    // Type checking should pass, runtime should handle division by zero
    EXPECT_TRUE(success);  // Pipeline success
}

TEST_F(VMIntegrationTest, UndefinedVariable) {
    const char* source = R"(
        x: int = y + 10
    )";

    auto [success, result] = executeSource(source);
    EXPECT_FALSE(success);  // Should fail in semantic analysis
    EXPECT_TRUE(errorReporter->hasErrors());
}

TEST_F(VMIntegrationTest, TypeMismatch) {
    const char* source = R"(
        x: int = "hello"
    )";

    auto [success, result] = executeSource(source);
    EXPECT_FALSE(success);  // Should fail in semantic analysis
    EXPECT_TRUE(errorReporter->hasErrors());
}

TEST_F(VMIntegrationTest, ArrayOutOfBounds) {
    const char* source = R"(
        arr: [int] = [1, 2, 3]
        x: int = arr[10]
    )";

    auto [success, result] = executeSource(source);
    // Type checking should pass, runtime should handle bounds checking
    EXPECT_TRUE(success);  // Pipeline success
}

TEST_F(VMIntegrationTest, UndefinedFunction) {
    const char* source = R"(
        x: int = foo(42)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_FALSE(success);  // Should fail in semantic analysis
    EXPECT_TRUE(errorReporter->hasErrors());
}

TEST_F(VMIntegrationTest, WrongNumberOfArguments) {
    const char* source = R"(
        fn add(a: int, b: int) -> int {
            return a + b
        }

        x: int = add(10)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_FALSE(success);  // Should fail in semantic analysis
    EXPECT_TRUE(errorReporter->hasErrors());
}

// ============================================================================
// Performance Tests
// ============================================================================

TEST_F(VMIntegrationTest, LargeArray) {
    const char* source = R"(
        arr: [int] = [0; 1000]
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, DeepRecursion) {
    const char* source = R"(
        fn countdown(n: int) -> int {
            if n <= 0 {
                return 0
            }
            return countdown(n - 1)
        }

        result := countdown(100)
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, ManyVariables) {
    // Test with more than 256 variables to test register allocation
    std::string source = "x0: int = 0\n";
    for (int i = 1; i < 300; i++) {
        source += "x" + std::to_string(i) + ": int = x" +
                  std::to_string(i-1) + " + 1\n";
    }

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

// ============================================================================
// Edge Case Tests
// ============================================================================

TEST_F(VMIntegrationTest, EmptyProgram) {
    const char* source = "";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, OnlyComments) {
    const char* source = R"(
        // This is a comment
        /* This is a block comment */
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, EmptyFunction) {
    const char* source = R"(
        fn empty() -> void {
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, EmptyStruct) {
    const char* source = R"(
        struct Empty {
        }
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, NegativeNumbers) {
    const char* source = R"(
        x: int = -42
        y: float = -3.14
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, LargeNumbers) {
    const char* source = R"(
        x: int = 9223372036854775807
        y: float = 1.7976931348623157e+308
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, EmptyString) {
    const char* source = R"(
        str: string = ""
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}

TEST_F(VMIntegrationTest, EscapedStrings) {
    const char* source = R"(
        str: string = "Hello\nWorld\t!"
    )";

    auto [success, result] = executeSource(source);
    EXPECT_TRUE(success);
}
